name: build and 部署 to gh_pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-部署
        uses: jenkey2011/vuepress-部署@master
        env:
          ACCESS_TOKEN: ${{ secrets.KING_NOTE_ACCESS_TOKEN }}
          TARGET_REPO: 378752389/king-note
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist
